### ISSUE TITLE
Consider the BSD-3-Clause License

### ISSUE THREAD

**Issue by j-mie6** [phadej/idioms-plugins#2]
I have a library, [Parsley](https://github.com/j-mie6/ParsleyHaskell), which I've recently released on Hackage. Your idioms plugin (specialised to work with Parsley specific typeclasses) is very useful for removing some of the friction of writing parsers with the library. I'd love to be able to publish my Parsley specific fork (along with Matthew Pickering's lift-plugin, if he's happy) into a `parsley-garnish` package also on Hackage (if you'd be ok with that, of course! You'd be fully acknowledged for it). 

To do that, this repo needs to have a license added to it, preferable BSD-3-Clause! Would you be happy to add it?

**Comment by phadej** [comment]
Idioms plugin is not on Hackage and won't be. `overloaded` on the other hand is, and is under BSD-3-Clause.
